package ventanas;

import javax.swing.WindowConstants;
import metodos.WindowTool;
import metodos.Validacion;
import clases.Usuario;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import metodos.Conexion;


public class Admin_AddUser extends javax.swing.JFrame {
    
    //Metodos.
    WindowTool Metodo = new WindowTool();
    Validacion Val = new Validacion();
    
    
    //Variables.
    String Username_Sesion;
    Date date2 = new Date(2010-1900, 11, 31);
    boolean Igual = false;
    Usuario User = new Usuario();
    
    //getting fecha de registro.
    java.sql.Date FechaRegistro = new java.sql.Date(LocalDate.now().getYear() - 1900, LocalDate.now().getMonthValue() - 1,
            LocalDate.now().getDayOfMonth());
    
    
    public Admin_AddUser() {
        
        initComponents();
        
        
        //Variables.
        Username_Sesion = Login.Username_Sesion;
        
        
        //Modelando.
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(1000, 600);
        this.setTitle(" -  Menu registro de usuario.");
        
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        //Fondo.
        Fondo_Lbl.setIcon(Metodo.SetFondo(Fondo_Lbl, "src/icons/Fondo2.jpg"));
        this.repaint();
        
        
        //Icono ventana.
        this.setIconImage(Metodo.GetIconImage("icons/Logo.jpg"));
        
        
        //Cambiando de panel.
        jPanel2.setVisible(false);
        W5_1.setVisible(false);

        
        //Dandole un rango valido a el calendario.
        Date date1 = new Date(1921-1900, 0, 1);
        
        Nacimiento_Txt.setDate(date2);
        Nacimiento_Txt.setSelectableDateRange(date1, date2);
        
        
        //Setting fecha de registro.
        FechaRegistro_Txt.setText(FechaRegistro.toString());
        
        
        //Setting Registrado por:.
        RegistradoBy_Txt.setText(Username_Sesion);
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo_Btn_group = new javax.swing.ButtonGroup();
        Titulo_Lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nombre_Txt = new javax.swing.JTextField();
        DNI_Txt = new javax.swing.JTextField();
        Edad_Txt = new javax.swing.JTextField();
        Masculino_RB = new javax.swing.JRadioButton();
        Femenino_RB = new javax.swing.JRadioButton();
        Nacimiento_Txt = new com.toedter.calendar.JDateChooser();
        Telefono_Txt = new javax.swing.JTextField();
        Email_Txt = new javax.swing.JTextField();
        Domicilio_Txt = new javax.swing.JTextField();
        Next_Btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        W1 = new javax.swing.JLabel();
        W2 = new javax.swing.JLabel();
        W3 = new javax.swing.JLabel();
        W5 = new javax.swing.JLabel();
        W4 = new javax.swing.JLabel();
        W6 = new javax.swing.JLabel();
        W7 = new javax.swing.JLabel();
        W8 = new javax.swing.JLabel();
        W5_1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Pass_Txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Username_Txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Estado_CMB = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        NivelAcceso_CMB = new javax.swing.JComboBox<>();
        Registrar_Btn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        FechaRegistro_Txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        RegistradoBy_Txt = new javax.swing.JTextField();
        Volver_Btn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Fondo_Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo_Lbl.setForeground(new java.awt.Color(204, 204, 204));
        Titulo_Lbl.setText("Menu registro de usuario.");
        getContentPane().add(Titulo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Información general");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Domicilio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 183, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Fecha de nacimiento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 351, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Información de contacto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("DNI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Sexo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        Nombre_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Nombre_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nombre_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Nombre_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nombre_TxtKeyPressed(evt);
            }
        });
        jPanel1.add(Nombre_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 363, -1));

        DNI_Txt.setBackground(new java.awt.Color(51, 51, 51));
        DNI_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DNI_Txt.setForeground(new java.awt.Color(204, 204, 204));
        DNI_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DNI_TxtKeyPressed(evt);
            }
        });
        jPanel1.add(DNI_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, 363, -1));

        Edad_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Edad_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Edad_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Edad_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Edad_TxtKeyPressed(evt);
            }
        });
        jPanel1.add(Edad_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, 363, -1));

        Masculino_RB.setBackground(new java.awt.Color(51, 51, 51));
        Sexo_Btn_group.add(Masculino_RB);
        Masculino_RB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Masculino_RB.setForeground(new java.awt.Color(204, 204, 204));
        Masculino_RB.setText("Masculino");
        Masculino_RB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Masculino_RBKeyPressed(evt);
            }
        });
        jPanel1.add(Masculino_RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        Femenino_RB.setBackground(new java.awt.Color(51, 51, 51));
        Sexo_Btn_group.add(Femenino_RB);
        Femenino_RB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Femenino_RB.setForeground(new java.awt.Color(204, 204, 204));
        Femenino_RB.setText("Femenino");
        Femenino_RB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Femenino_RBKeyPressed(evt);
            }
        });
        jPanel1.add(Femenino_RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 290, -1, -1));

        Nacimiento_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Nacimiento_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Nacimiento_Txt.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(Nacimiento_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 377, 363, -1));

        Telefono_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Telefono_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Telefono_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Telefono_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Telefono_TxtKeyPressed(evt);
            }
        });
        jPanel1.add(Telefono_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 75, 363, -1));

        Email_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Email_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Email_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Email_TxtKeyPressed(evt);
            }
        });
        jPanel1.add(Email_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 142, 363, -1));

        Domicilio_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Domicilio_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Domicilio_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Domicilio_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Domicilio_TxtKeyPressed(evt);
            }
        });
        jPanel1.add(Domicilio_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 209, 363, -1));

        Next_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Next_Btn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Next_Btn.setForeground(new java.awt.Color(204, 204, 204));
        Next_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_x32/Siguiente x48.png"))); // NOI18N
        Next_Btn.setText("Siguiente");
        Next_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Next_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 276, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Teléfono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 49, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Email:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 116, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Edad:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, -1, -1));

        W1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        W2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        W3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        W5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W5.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        W4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W4.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        W6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W6.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 20, 10));

        W7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 20, 10));

        W8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        W8.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(W8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 20, 10));

        W5_1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        W5_1.setForeground(new java.awt.Color(204, 204, 204));
        W5_1.setText("Asegúrate de cambiar esta fecha por defecto.");
        jPanel1.add(W5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 405, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 940, 440));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Información de acceso");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Password:");

        Pass_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Pass_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pass_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Pass_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Pass_TxtKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Username:");

        Username_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Username_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Username_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Username_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Username_TxtKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Nivel de acceso:");

        Estado_CMB.setBackground(new java.awt.Color(51, 51, 51));
        Estado_CMB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Estado_CMB.setForeground(new java.awt.Color(204, 204, 204));
        Estado_CMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        Estado_CMB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Estado_CMBKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Estado:");

        NivelAcceso_CMB.setBackground(new java.awt.Color(51, 51, 51));
        NivelAcceso_CMB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NivelAcceso_CMB.setForeground(new java.awt.Color(204, 204, 204));
        NivelAcceso_CMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Responsable De Bodega", "Auxiliar De Nomina" }));
        NivelAcceso_CMB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NivelAcceso_CMBKeyPressed(evt);
            }
        });

        Registrar_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Registrar_Btn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Registrar_Btn.setForeground(new java.awt.Color(204, 204, 204));
        Registrar_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_x32/AgregarUsuario x32.png"))); // NOI18N
        Registrar_Btn.setText("Registrar usuario");
        Registrar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_BtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Información adicional");

        FechaRegistro_Txt.setBackground(new java.awt.Color(51, 51, 51));
        FechaRegistro_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FechaRegistro_Txt.setForeground(new java.awt.Color(204, 204, 204));
        FechaRegistro_Txt.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Registrado por:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Fecha de registro");

        RegistradoBy_Txt.setBackground(new java.awt.Color(51, 51, 51));
        RegistradoBy_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RegistradoBy_Txt.setForeground(new java.awt.Color(204, 204, 204));
        RegistradoBy_Txt.setEnabled(false);

        Volver_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Volver_Btn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Volver_Btn.setForeground(new java.awt.Color(204, 204, 204));
        Volver_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_x32/Volver.png"))); // NOI18N
        Volver_Btn.setText("Volver");
        Volver_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_BtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Username_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(Pass_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(NivelAcceso_CMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Estado_CMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(FechaRegistro_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegistradoBy_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Registrar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Volver_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaRegistro_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistradoBy_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NivelAcceso_CMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Estado_CMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Registrar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(Volver_Btn)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 930, 440));
        getContentPane().add(Fondo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Next_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_BtnActionPerformed
        
        //Reset warnings.
        W1.setText("");
        W2.setText("");
        W3.setText("");
        W4.setText("");
        W5.setText("");
        W5_1.setVisible(false);
        W6.setText("");
        W7.setText("");
        W8.setText("");
        Igual = false;
        
        //Variables.
        int V = 0;
        
        
        //Validando campos vacios.
        if(Nombre_Txt.getText().equals("")){
            
            V++;
            W1.setText("!");
            
        }if(DNI_Txt.getText().equals("")){
            
            V++;
            W2.setText("!");
            
        }if(Edad_Txt.getText().equals("")){
            
            V++;
            W3.setText("!");
            
        }if(!Masculino_RB.isSelected() && !Femenino_RB.isSelected()){
            
            V++;
            W4.setText("!");
            
        }if(Nacimiento_Txt.getDate().compareTo(date2) == 0){
            
            Igual = true;
            W5.setText("!");
            W5_1.setVisible(true);
            
        }if(Telefono_Txt.getText().equals("")){
            
            V++;
            W6.setText("!");
            
        }if(Email_Txt.getText().equals("")){
            
            V++;
            W7.setText("!");
            
        }if(Domicilio_Txt.getText().equals("")){
            
            V++;
            W8.setText("!");
            
        }
        
        
        if(V == 0){
            
            if(Igual == false){
                
                if(Val.IsAnInt(Edad_Txt.getText())){
                
                    Date temp = Nacimiento_Txt.getDate();
                    java.sql.Date Nacimiento = new java.sql.Date(temp.getTime());


                    if( (Integer.parseInt(Edad_Txt.getText())) == Val.GetEdadByFn(Nacimiento) ){

                        //Obteniendo datos ingresados.
                        User.setNombre(Nombre_Txt.getText().trim());
                        User.setDNI(DNI_Txt.getText().trim());
                        User.setEdad(Integer.parseInt(Edad_Txt.getText().trim()));
                        User.setSexo(Val.GetSelectedSex(Masculino_RB, Femenino_RB));
                        User.setFechaDeNacimiento(Nacimiento);
                        User.setTelefono(Telefono_Txt.getText().trim());
                        User.setEmail(Email_Txt.getText().trim());
                        User.setDomicilio(Domicilio_Txt.getText().trim());


                        jPanel1.setVisible(false);
                        jPanel2.setVisible(true);  
                        
                        Username_Txt.requestFocus();

                    }else{

                        int Option = JOptionPane.showConfirmDialog(null, "Edad errónea para la fecha de nacimiento ingresada.\n"
                                + "¿Desea editar el campo por una edad válida?\nEdad válida: "+ Val.GetEdadByFn(Nacimiento),
                                " -  Mensaje de advertencia", JOptionPane.YES_NO_OPTION, 0,
                                Metodo.GetIcon("src/JOIcons/Advertencia JO.png"));
                                
                        if(Option == JOptionPane.YES_OPTION){

                            Edad_Txt.setText(Integer.toString(Val.GetEdadByFn(Nacimiento)));

                        }

                    }

                }else{

                    JOptionPane.showMessageDialog(null, "Por favor, ingresa una edad válida.\n(Sólo numeros enteros).",
                            " -  Mensaje de advertencia", 0, Metodo.GetIcon("src/JOIcons/Advertencia JO.png"));                               

                    Edad_Txt.setText("");
                    W3.setText("!");

                }
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Asegurate de cambiar la fecha de nacimiento por defecto.",
                        " -  Mensaje de advertencia", 0, Metodo.GetIcon("src/JOIcons/Advertencia JO.png"));

            }
            
        }else{
      
            JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos vacios.", " -  Mensaje de advertencia",
                0, Metodo.GetIcon("src/JOIcons/Advertencia JO.png"));
            
        }
 
    }//GEN-LAST:event_Next_BtnActionPerformed

    private void Volver_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_BtnActionPerformed
        
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        
    }//GEN-LAST:event_Volver_BtnActionPerformed

    private void Registrar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_BtnActionPerformed
        
        //Reset Warnings.
        jLabel17.setText("");
        jLabel20.setText("");
        
        
        //Variables.
        int V1 = 0;
        
        String NivelAcceso = Val.GetSelectedAccess(NivelAcceso_CMB.getSelectedIndex());
        String Estado = Val.GetSelectedStat(Estado_CMB.getSelectedIndex());
        
        
        //Validando que no hayan campos vacios.
        if(Username_Txt.getText().equals("")){
            
            jLabel17.setText("!");
            V1++;
            
        }if(Pass_Txt.getText().equals("")){
            
            jLabel20.setText("!");
            V1++;
            
        }      
        
        
        if(V1 == 0){
            
            //Obteniendo los datos ingresados.
            User.setUsername(Username_Txt.getText().trim());
            User.setPassword(Pass_Txt.getText().trim());
            User.setNivelAcceso(NivelAcceso);
            User.setEstado(Estado);
            User.setFechaRegistro(FechaRegistro);
            User.setRegistradoBy(Username_Sesion);
            
            //Añadiendo usuario a la BD.
            try {
                
                Connection cn = Conexion.Conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select Username from Usuarios where Username = '"+ User.getUsername() +"'");
                
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    
                    JOptionPane.showMessageDialog(null, "Nombre de usuario en uso, por favor elige otro.",
                            " -  Mensaje de advertencia", 0, Metodo.GetIcon("src/JOIcons/Advertencia JO.png"));
                    
                    jLabel17.setText("!");
                    
                }else{
                    
                    try {
                        
                        Connection cn2 = Conexion.Conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                                "insert into Usuarios values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        
                        pst2.setInt(1, 0);
                        pst2.setString(2, User.getNombre());
                        pst2.setString(3, User.getDNI());
                        pst2.setInt(4, User.getEdad());
                        pst2.setString(5, User.getSexo());
                        pst2.setString(6, User.getTelefono());
                        pst2.setString(7, User.getEmail());
                        pst2.setString(8, User.getDomicilio());
                        pst2.setDate(9, User.getFechaDeNacimiento());
                        pst2.setString(10, User.getUsername());
                        pst2.setString(11, User.getPassword());
                        pst2.setString(12, User.getNivelAcceso());
                        pst2.setString(13, "");
                        pst2.setString(14, "");
                        pst2.setString(15, Username_Sesion);
                        pst2.setDate(16, FechaRegistro);
                        pst2.setString(17, Estado);
                        pst2.setInt(18, 0);
                        pst2.setString(19, "");
                        pst2.executeUpdate();
                        
                        cn.close();
                        cn2.close();
                        
                        JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente!", " -  Mensaje de información",
                                0, Metodo.GetIcon("src/JOIcons/Info JO.png"));
                        this.dispose();
                        
                    } catch (SQLException e) {
                        
                        System.err.println("Error al registrar nuevo usuario. "+ e);
                        JOptionPane.showMessageDialog(null, "Error de conexiòn.", " -  Mensaje de error",
                                0, Metodo.GetIcon("src/JOIcons/ErrorConexion JO.png"));
                        
                    }
                    
                }
 
            } catch (SQLException e) {
                
                System.err.println("Error al validar nuevo usuario. "+ e);
                
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos vacios.", " -  Mensaje de advertencia",
                    0, Metodo.GetIcon("src/JOIcons/Advertencia JO.png"));
            
        }
        
    }//GEN-LAST:event_Registrar_BtnActionPerformed

    private void Nombre_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre_TxtKeyPressed
        
        Metodo.WaitEnter(evt, DNI_Txt);
        
    }//GEN-LAST:event_Nombre_TxtKeyPressed

    private void DNI_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DNI_TxtKeyPressed
        
        Metodo.WaitEnter(evt, Edad_Txt);
        
    }//GEN-LAST:event_DNI_TxtKeyPressed

    private void Edad_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Edad_TxtKeyPressed
        
        Metodo.WaitEnter(evt, Masculino_RB);
        
    }//GEN-LAST:event_Edad_TxtKeyPressed

    private void Masculino_RBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Masculino_RBKeyPressed
        
        int cTeclaPresionada = evt.getKeyCode();
        
        if(cTeclaPresionada == 39){
            
            Femenino_RB.requestFocus();
            
        }else if(cTeclaPresionada == KeyEvent.VK_ENTER){
            
            Masculino_RB.setSelected(true);
            Telefono_Txt.requestFocus();
            
        }
        
    }//GEN-LAST:event_Masculino_RBKeyPressed

    private void Femenino_RBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Femenino_RBKeyPressed
        
        int cTeclaPresionada = evt.getKeyCode();
        
        if(cTeclaPresionada == 37){
            
            Masculino_RB.requestFocus();
            
        }else if(cTeclaPresionada == KeyEvent.VK_ENTER){
            
            Femenino_RB.setSelected(true);
            Telefono_Txt.requestFocus();
            
        }
        
    }//GEN-LAST:event_Femenino_RBKeyPressed

    private void Telefono_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Telefono_TxtKeyPressed
        
        Metodo.WaitEnter(evt, Email_Txt);
        
    }//GEN-LAST:event_Telefono_TxtKeyPressed

    private void Email_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Email_TxtKeyPressed
        
        Metodo.WaitEnter(evt, Domicilio_Txt);
        
    }//GEN-LAST:event_Email_TxtKeyPressed

    private void Domicilio_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Domicilio_TxtKeyPressed
       
        Metodo.WaitEnter(evt, Next_Btn);
        
    }//GEN-LAST:event_Domicilio_TxtKeyPressed

    private void Username_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Username_TxtKeyPressed
        
        Metodo.WaitEnter(evt, Pass_Txt);
        
    }//GEN-LAST:event_Username_TxtKeyPressed

    private void Pass_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pass_TxtKeyPressed
        
        int Key = evt.getKeyCode();
        
        if(Key == KeyEvent.VK_ENTER){
            
            NivelAcceso_CMB.requestFocus();
            
        }
        
    }//GEN-LAST:event_Pass_TxtKeyPressed

    private void NivelAcceso_CMBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NivelAcceso_CMBKeyPressed
        
        int Key = evt.getKeyCode();
        
        if(Key == KeyEvent.VK_ENTER){
            
            Estado_CMB.requestFocus();
            
        }
        
    }//GEN-LAST:event_NivelAcceso_CMBKeyPressed

    private void Estado_CMBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Estado_CMBKeyPressed
        
        Metodo.WaitEnter(evt, Registrar_Btn);
        
    }//GEN-LAST:event_Estado_CMBKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNI_Txt;
    private javax.swing.JTextField Domicilio_Txt;
    private javax.swing.JTextField Edad_Txt;
    private javax.swing.JTextField Email_Txt;
    private javax.swing.JComboBox<String> Estado_CMB;
    private javax.swing.JTextField FechaRegistro_Txt;
    private javax.swing.JRadioButton Femenino_RB;
    private javax.swing.JLabel Fondo_Lbl;
    private javax.swing.JRadioButton Masculino_RB;
    private com.toedter.calendar.JDateChooser Nacimiento_Txt;
    private javax.swing.JButton Next_Btn;
    private javax.swing.JComboBox<String> NivelAcceso_CMB;
    private javax.swing.JTextField Nombre_Txt;
    private javax.swing.JTextField Pass_Txt;
    private javax.swing.JTextField RegistradoBy_Txt;
    private javax.swing.JButton Registrar_Btn;
    private javax.swing.ButtonGroup Sexo_Btn_group;
    private javax.swing.JTextField Telefono_Txt;
    private javax.swing.JLabel Titulo_Lbl;
    private javax.swing.JTextField Username_Txt;
    private javax.swing.JButton Volver_Btn;
    private javax.swing.JLabel W1;
    private javax.swing.JLabel W2;
    private javax.swing.JLabel W3;
    private javax.swing.JLabel W4;
    private javax.swing.JLabel W5;
    private javax.swing.JLabel W5_1;
    private javax.swing.JLabel W6;
    private javax.swing.JLabel W7;
    private javax.swing.JLabel W8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
