package ventanas;

import javax.swing.WindowConstants;
import java.sql.*;
import javax.swing.JOptionPane;
import metodos.WindowTool;
import metodos.Conexion;


public class Login_ResetPass extends javax.swing.JFrame {

    WindowTool WinTool = new WindowTool();
    String Username = Login_RecoverPass.Username;
    
    public Login_ResetPass() {
        
        initComponents();
        
        
        //Metodos.
        WindowTool WinTool = new WindowTool();
        
        
        //Modelando ventana.
        this.setResizable(false);
        this.setTitle(" -  Restablecer contraseña.");
        this.setSize(500, 350);
        this.setLocationRelativeTo(null);
        
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        
        //Setting fondo.
        Fondo_Lbl.setIcon(WinTool.SetFondo(Fondo_Lbl, "src/icons/Fondo2.jpg"));
        this.repaint();
        
        //Setting icon.
        this.setIconImage(WinTool.GetIconImage("icons/Logo.jpg"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_Lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Restaurar_Btn = new javax.swing.JButton();
        NewPass_Txt = new javax.swing.JPasswordField();
        ConfirmPass_Txt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VerPass_CB = new javax.swing.JCheckBox();
        Fondo_Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Titulo_Lbl.setForeground(new java.awt.Color(204, 204, 204));
        Titulo_Lbl.setText("Crear nueva contraseña");
        getContentPane().add(Titulo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 10, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("<html>A continuación, introduce tu nueva contraseña:<html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Confirma tu contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        Restaurar_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Restaurar_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Restaurar_Btn.setForeground(new java.awt.Color(204, 204, 204));
        Restaurar_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_x32/Restaurar contraseña x32.png"))); // NOI18N
        Restaurar_Btn.setText("Restaurar contraseña");
        Restaurar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restaurar_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Restaurar_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        NewPass_Txt.setBackground(new java.awt.Color(51, 51, 51));
        NewPass_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewPass_Txt.setForeground(new java.awt.Color(204, 204, 204));
        NewPass_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NewPass_TxtKeyPressed(evt);
            }
        });
        getContentPane().add(NewPass_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, -1));

        ConfirmPass_Txt.setBackground(new java.awt.Color(51, 51, 51));
        ConfirmPass_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConfirmPass_Txt.setForeground(new java.awt.Color(204, 204, 204));
        ConfirmPass_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConfirmPass_TxtKeyPressed(evt);
            }
        });
        getContentPane().add(ConfirmPass_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 10, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 10, 10));

        VerPass_CB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VerPass_CB.setForeground(new java.awt.Color(204, 204, 204));
        VerPass_CB.setText("Ver contraseña");
        VerPass_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPass_CBActionPerformed(evt);
            }
        });
        getContentPane().add(VerPass_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        getContentPane().add(Fondo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmPass_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConfirmPass_TxtKeyPressed
        
        WinTool.WaitEnter(evt, Restaurar_Btn);
        
    }//GEN-LAST:event_ConfirmPass_TxtKeyPressed

    private void NewPass_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewPass_TxtKeyPressed
        
        WinTool.WaitEnter(evt, ConfirmPass_Txt);
        
    }//GEN-LAST:event_NewPass_TxtKeyPressed

    private void Restaurar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restaurar_BtnActionPerformed
        
        //Reset warnings.
        jLabel3.setText("");
        jLabel4.setText("");
        
        String NewPass, ConfirmPass;
        int Val = 0;
        
        NewPass = NewPass_Txt.getText().trim();
        ConfirmPass = ConfirmPass_Txt.getText().trim();
        
        if(NewPass.equals("")){
            
            jLabel4.setText("*");
            Val++;
            
        }if(ConfirmPass.equals("")){
            
            jLabel3.setText("*");
            Val++;
            
        }
        
        if(NewPass.equalsIgnoreCase(ConfirmPass)){
            
            if(Val == 0){
                
                try{
                
                    Connection cn = Conexion.Conectar();
                    PreparedStatement pst = cn.prepareStatement(
                            "update Usuarios set Password = ? where Username = '"+ Username +"'");

                    pst.setString(1, NewPass);
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null, "Se ha restablecido tu contraseña!", " -  Mensaje de información",
                                        0, WinTool.GetIcon("src/JOIcons/Info JO.png"));
                    
                    this.dispose();
                
                }catch(SQLException e){
                
                    System.err.println("error al actualizar contraseña. "+ e);
                    JOptionPane.showMessageDialog(null, "Error de conexión.", " -  Mensaje de error",
                                        0, WinTool.GetIcon("src/JOIcons/ErrorConexion JO.png"));
                
                 }
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Debes llenar ambos campos.", " -  Mensaje de advertencia",
                                        0, WinTool.GetIcon("src/JOIcons/Advertencia JO.png"));
                
            }
            
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.", " -  Mensaje de advertencia",
                                        0, WinTool.GetIcon("src/JOIcons/Advertencia JO.png"));
                       
        }
        
    }//GEN-LAST:event_Restaurar_BtnActionPerformed

    private void VerPass_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPass_CBActionPerformed
        
        WinTool.VerContraseña(VerPass_CB, NewPass_Txt, ConfirmPass_Txt);
        
    }//GEN-LAST:event_VerPass_CBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_ResetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPass_Txt;
    private javax.swing.JLabel Fondo_Lbl;
    private javax.swing.JPasswordField NewPass_Txt;
    private javax.swing.JButton Restaurar_Btn;
    private javax.swing.JLabel Titulo_Lbl;
    private javax.swing.JCheckBox VerPass_CB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
