package ventanas;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import metodos.WindowTool;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import metodos.Conexion;
import metodos.FicheroTool;



public class Login extends javax.swing.JFrame {

    //Metodos.
    WindowTool WinTool = new WindowTool();
    FicheroTool FiTool = new FicheroTool();
    
    //Variables GLOBALES.
    public static String Username_Sesion = "";
    public static String PreguntaSecreta = "";
    public static int NumeroDeSesion = 0;
    public static String Nombre_Sesion = "";
    public static String Sexo_Sesion = "";
    public static String Acceso = "";
    
    
    //Variables.
    String Pass = "";
    
    
    public Login() {
        
        initComponents();
       
        
        //Modelando el Jframe de Login.
        this.setVisible(true);
        this.setSize(550, 700);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle(" -  Acceso al sistema.");
        
        //Setting Close operation.
        try {
            
            this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
               
               @Override
               public void windowClosing(WindowEvent e){
                   
                   int Option = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas salir?",
                           " -  Mensaje de advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                                WinTool.GetIcon("src/JOIcons/Advertencia JO.png"));
                   
                   if(Option == JOptionPane.YES_OPTION){
                       
                       System.exit(0);
                       
                   }
                   
               } 
                
            });
            
        } catch (Exception e) {
            
            System.err.println(e);
            
        }
        
        
        //Agregando el fondo de pantalla de Login.
        Fondo_Lbl.setIcon(WinTool.SetFondo(Fondo_Lbl, "src/icons/Fondo2.jpg"));
        this.repaint();
        
        
        //Agregando el logo del programa a la ventana Login.
        Logo_Lbl.setIcon(WinTool.SetFondo(Logo_Lbl, "src/icons/Logo.jpg"));
        this.repaint();
        
        
        //Agregando un icono a la ventana Login.
        this.setIconImage(WinTool.GetIconImage("icons/Logo.jpg"));
        
        
        //Recordar datos de acceso.   
        String U = FiTool.GetUserFichero();
        String P = FiTool.GetPassFichero();
        
        if( (U.equalsIgnoreCase("")) == false ){
            
            jFrame1.setVisible(true);
            jFrame1.setSize(350, 250);
            jFrame1.setLocationRelativeTo(null);
            jFrame1.setTitle(" -  Inicio de sesión activo.");
            Fondo_Lbl2.setIcon(WinTool.SetFondo(Fondo_Lbl2, "src/icons/Fondo2.jpg"));
            jFrame1.setIconImage(WinTool.GetIconImage("icons/Logo.jpg"));
          
            jFrame1.setAlwaysOnTop(true);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Titulo_Lbl = new javax.swing.JLabel();
        Si_Btn1 = new javax.swing.JButton();
        No_Btn = new javax.swing.JButton();
        Fondo_Lbl2 = new javax.swing.JLabel();
        Logo_Lbl = new javax.swing.JLabel();
        User_Txt = new javax.swing.JTextField();
        Pass_Txt = new javax.swing.JPasswordField();
        Username_Lbl = new javax.swing.JLabel();
        Pass_Lbl = new javax.swing.JLabel();
        Login_Btn = new javax.swing.JButton();
        ForgetPass_Lbl = new javax.swing.JLabel();
        VerPass_CB = new javax.swing.JCheckBox();
        MantenerS_CB = new javax.swing.JCheckBox();
        Fondo_Lbl = new javax.swing.JLabel();

        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Titulo_Lbl.setForeground(new java.awt.Color(204, 204, 204));
        Titulo_Lbl.setText("<html>Ya tienes un inicio de sesión activo.<p><p>"
            + "Deseas continuar como "+ FiTool.GetUserFichero() +""
            + "?<html>");
        jFrame1.getContentPane().add(Titulo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 260, 80));

        Si_Btn1.setBackground(new java.awt.Color(51, 51, 51));
        Si_Btn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Si_Btn1.setForeground(new java.awt.Color(204, 204, 204));
        Si_Btn1.setText("Si, continuar");
        Si_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Si_Btn1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(Si_Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        No_Btn.setBackground(new java.awt.Color(51, 51, 51));
        No_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        No_Btn.setForeground(new java.awt.Color(204, 204, 204));
        No_Btn.setText("No, cerrar sesión");
        No_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_BtnActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(No_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 150, -1));
        jFrame1.getContentPane().add(Fondo_Lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Logo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 270, 270));

        User_Txt.setBackground(new java.awt.Color(51, 51, 51));
        User_Txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        User_Txt.setForeground(new java.awt.Color(204, 204, 204));
        User_Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_Txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User_Txt.setSelectionColor(new java.awt.Color(0, 0, 0));
        User_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_TxtActionPerformed(evt);
            }
        });
        User_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                User_TxtKeyPressed(evt);
            }
        });
        getContentPane().add(User_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 370, 30));

        Pass_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Pass_Txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Pass_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Pass_Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pass_Txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pass_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_TxtActionPerformed(evt);
            }
        });
        Pass_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Pass_TxtKeyPressed(evt);
            }
        });
        getContentPane().add(Pass_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 370, 30));

        Username_Lbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Username_Lbl.setForeground(new java.awt.Color(204, 204, 204));
        Username_Lbl.setText("Username:");
        getContentPane().add(Username_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 370, 80, -1));

        Pass_Lbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Pass_Lbl.setForeground(new java.awt.Color(204, 204, 204));
        Pass_Lbl.setText("Password:");
        getContentPane().add(Pass_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 460, 80, -1));

        Login_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Login_Btn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Login_Btn.setForeground(new java.awt.Color(204, 204, 204));
        Login_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_x32/IniciarSesion x32.png"))); // NOI18N
        Login_Btn.setText("Login");
        Login_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BtnActionPerformed(evt);
            }
        });
        Login_Btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Login_BtnKeyPressed(evt);
            }
        });
        getContentPane().add(Login_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 555, 120, -1));

        ForgetPass_Lbl.setForeground(new java.awt.Color(204, 204, 204));
        ForgetPass_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgetPass_Lbl.setText("He olvidado mi contraseña.");
        ForgetPass_Lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetPass_LblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgetPass_LblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgetPass_LblMouseExited(evt);
            }
        });
        getContentPane().add(ForgetPass_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 150, 20));

        VerPass_CB.setForeground(new java.awt.Color(204, 204, 204));
        VerPass_CB.setText("Mostrar contraseña");
        VerPass_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPass_CBActionPerformed(evt);
            }
        });
        getContentPane().add(VerPass_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, -1, 20));

        MantenerS_CB.setForeground(new java.awt.Color(204, 204, 204));
        MantenerS_CB.setText("Mantener sesión iniciada");
        MantenerS_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenerS_CBActionPerformed(evt);
            }
        });
        getContentPane().add(MantenerS_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 160, -1));

        Fondo_Lbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Fondo_Lbl.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Fondo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_TxtActionPerformed
        
   
        
    }//GEN-LAST:event_User_TxtActionPerformed

    private void Login_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BtnActionPerformed

        //Opteniendo los datos de acceso.
        Username_Sesion = User_Txt.getText().trim();
        Pass = Pass_Txt.getText().trim();
        
        //Validando que no haya campos vacios.
        if(!Username_Sesion.equals("") && !Pass.equals("")){
            
            try{
                
                Connection cn = Conexion.Conectar();
                PreparedStatement pst = cn.prepareStatement(
                    "select NumeroDeSesion, NivelAcceso, Estado, Nombre, PreguntaSecreta,"
                            + "Sexo from Usuarios where Username = '"+ Username_Sesion +"' and Password = '"+ Pass +"'");                        
                        
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                                        
                    String Estado = rs.getString("Estado");
                    
                    Acceso = rs.getString("NivelAcceso");
                    PreguntaSecreta = rs.getString("PreguntaSecreta");
                    NumeroDeSesion = rs.getInt("NumeroDeSesion");
                    Nombre_Sesion = rs.getString("Nombre");
                    Sexo_Sesion = rs.getString("Sexo");
                    
                    //Validando estado.
                    if(Estado.equalsIgnoreCase("Activo")){
                        
                        if(Acceso.equalsIgnoreCase("Administrador")){
                                                                               
                            File file = new File("C:\\Users\\"+ System.getProperty("user.name") +"\\Documents\\NetBeansProjects\\"
                                    + "Evolution\\1.MostrarAyuda"+ Username_Sesion +".txt");
                            
                            if(!file.exists()){
                                
                                FiTool.EscrbirFichero("Si", Username_Sesion, 1);
                                
                            }
                            
                            if(MantenerS_CB.isSelected()){
                                
                                FiTool.EscrbirFichero(Username_Sesion, Pass);
                                
                            }else{
                                
                                FiTool.LimpiarFichero();
                                
                            }
                            
                            
                            if(NumeroDeSesion == 0 || NumeroDeSesion == 1){
                                
                                NumeroDeSesion++;
                                
                                try{
                        
                                    Connection cn2 = Conexion.Conectar();
                                    PreparedStatement pst2 = cn2.prepareStatement(
                                        "update Usuarios set NumeroDeSesion = ? where Username = '"+ 
                                            Username_Sesion +"'");

                                    String NS = Integer.toString(NumeroDeSesion);

                                    pst2.setString(1, NS);
                                    pst2.executeUpdate();


                                    cn2.close();

                                }catch(SQLException e){

                                    System.err.println("Error al actualizar NumeroDeSesion "+ e);
                                    JOptionPane.showMessageDialog(null, "Error de conexión.", " -  Mensaje de error",
                                        0, WinTool.GetIcon("src/JOIcons/ErrorConexion JO.png"));

                                }
                                
                                this.dispose();
                                new Administrador().setVisible(true);
                                
                                if(NumeroDeSesion == 1){
                                                                        
                                    new Login_SetRecovery().setVisible(true);
                                    
                                }                           
                                
                            }else{
                                
                                this.dispose();
                                new Administrador().setVisible(true);
                                
                            }
                                                                                    
                            JOptionPane.showMessageDialog(null, "Sesión iniciada como Administrador.", " -  Mensaje de información",
                                        0, WinTool.GetIcon("src/JOIcons/Info JO.png"));
                        
                        }else if(Acceso.equalsIgnoreCase("Responsable De Bodega")){
                            
                            File file = new File("C:\\Users\\rolan\\Documents\\NetBeansProjects\\Evolution\\1.MostrarAyuda"
                                    + Username_Sesion +".txt");
                            
                            if(!file.exists()){
                                
                                FiTool.EscrbirFichero("Si", Username_Sesion, 1);
                                
                            }
                            
                            if(MantenerS_CB.isSelected()){
                                
                                FiTool.EscrbirFichero(Username_Sesion, Pass);
                                
                            }else{
                                
                                FiTool.LimpiarFichero();
                                
                            }
                            
                            
                            if(NumeroDeSesion == 0 || NumeroDeSesion == 1){
                                
                                NumeroDeSesion++;
                                
                                try{
                        
                                    Connection cn2 = Conexion.Conectar();
                                    PreparedStatement pst2 = cn2.prepareStatement(
                                        "update Usuarios set NumeroDeSesion = ? where Username = '"+ 
                                            Username_Sesion +"'");

                                    String NS = Integer.toString(NumeroDeSesion);

                                    pst2.setString(1, NS);
                                    pst2.executeUpdate();


                                    cn2.close();

                                }catch(SQLException e){

                                    System.err.println("Error al actualizar NumeroDeSesion "+ e);
                                    JOptionPane.showMessageDialog(null, "Error de conexión.", " -  Mensaje de error",
                                        0, WinTool.GetIcon("src/JOIcons/ErrorConexion JO.png"));

                                }
                                
                                this.dispose();
                                new ResponsableDeBodega().setVisible(true);
                                
                                if(NumeroDeSesion == 1){
                                    
                                    new Login_SetRecovery().setVisible(true);
                                    
                                }                                                     
                                
                            }else{
                                
                                this.dispose();
                                new ResponsableDeBodega().setVisible(true);
                                
                            }
                            
                            FiTool.EscrbirFichero("Si", Username_Sesion, 1);
                            
                            JOptionPane.showMessageDialog(null, "Sesión iniciada como Responsable De Bodega.", " -  Mensaje de información",
                                        0, WinTool.GetIcon("src/JOIcons/Info JO.png"));

                        }else if(Acceso.equalsIgnoreCase("Auxiliar De Nomina")){
                            
                            File file = new File("C:\\Users\\rolan\\Documents\\NetBeansProjects\\Evolution\\1.MostrarAyuda"
                                    + Username_Sesion +".txt");
                            
                            if(!file.exists()){
                                
                                FiTool.EscrbirFichero("Si", Username_Sesion, 1);
                                
                            }
                            
                            if(MantenerS_CB.isSelected()){
                                
                                FiTool.EscrbirFichero(Username_Sesion, Pass);
                                
                            }else{
                                
                                FiTool.LimpiarFichero();
                                
                            }
                            
                            
                            if(NumeroDeSesion == 0 || NumeroDeSesion == 1){
                                
                                NumeroDeSesion++;
                                
                                try{
                        
                                    Connection cn2 = Conexion.Conectar();
                                    PreparedStatement pst2 = cn2.prepareStatement(
                                        "update Usuarios set NumeroDeSesion = ? where Username = '"+ 
                                            Username_Sesion +"'");

                                    String NS = Integer.toString(NumeroDeSesion);

                                    pst2.setString(1, NS);
                                    pst2.executeUpdate();


                                    cn2.close();

                                }catch(SQLException e){

                                    System.err.println("Error al actualizar NumeroDeSesion "+ e);
                                    JOptionPane.showMessageDialog(null, "Error de conexión.", " -  Mensaje de error",
                                        0, WinTool.GetIcon("src/JOIcons/ErrorConexion JO.png"));

                                }
                                
                                this.dispose();
                                new _AuxNom().setVisible(true);
                                
                                if(NumeroDeSesion == 1){
                                    
                                    new Login_SetRecovery().setVisible(true);
                                    
                                }                                                         
                                
                            }else{
                                
                                this.dispose();
                                new _AuxNom().setVisible(true);
                                
                            }

                            FiTool.EscrbirFichero("Si", Username_Sesion, 1);
                            
                            JOptionPane.showMessageDialog(null, "Sesión iniciada como Auxiliar De Nomina.", " -  Mensaje de información",
                                        0, WinTool.GetIcon("src/JOIcons/Info JO.png"));
                            
                        }  
                        
                    }else{
                        
                        JOptionPane.showMessageDialog(null, "Usuario inhabilitado.", " -  Mensaje de advertencia",
                                        0, WinTool.GetIcon("src/JOIcons/Advertencia JO.png"));
                        User_Txt.setText("");
                        Pass_Txt.setText("");
                        User_Txt.requestFocus();
                        
                    }                             
                    
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Datos de acceso erróneos.", " -  Mensaje de error",
                                        0, WinTool.GetIcon("src/JOIcons/Error JO.png"));
                    User_Txt.setText("");
                    Pass_Txt.setText("");
                    User_Txt.requestFocus();
                    
                }
                
                cn.close();
                
            }catch(SQLException e){
                
                System.err.println("Error en el boton acceder: "+ e);
                JOptionPane.showMessageDialog(null, "Error de conexión.", " -  Mensaje de error",
                                        0, WinTool.GetIcon("src/JOIcons/ErrorConexion JO.png"));
                
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Por favor, rellenar todos los campos.", " -  Mensaje de advertencia",
                                        0, WinTool.GetIcon("src/JOIcons/Advertencia JO.png"));
            User_Txt.requestFocus();
            
            User_Txt.setText("");
            Pass_Txt.setText("");
            
        }
        
    }//GEN-LAST:event_Login_BtnActionPerformed

    private void Pass_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_TxtActionPerformed
        
        
    }//GEN-LAST:event_Pass_TxtActionPerformed

    private void ForgetPass_LblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPass_LblMouseEntered
        
        ForgetPass_Lbl.setForeground(new Color(0, 153, 255));
        
    }//GEN-LAST:event_ForgetPass_LblMouseEntered

    private void ForgetPass_LblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPass_LblMouseExited
        
        ForgetPass_Lbl.setForeground(new Color(204, 204, 204));
        
    }//GEN-LAST:event_ForgetPass_LblMouseExited

    private void ForgetPass_LblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPass_LblMouseClicked
        
        new Login_RecoverPass().setVisible(true);
        
    }//GEN-LAST:event_ForgetPass_LblMouseClicked

    private void Login_BtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_BtnKeyPressed
        
        WinTool.WaitEnter(evt, Login_Btn);
        
    }//GEN-LAST:event_Login_BtnKeyPressed

    private void VerPass_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPass_CBActionPerformed

        WinTool.VerContraseña(VerPass_CB, Pass_Txt);

    }//GEN-LAST:event_VerPass_CBActionPerformed

    private void User_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_User_TxtKeyPressed

        WinTool.WaitEnter(evt, Pass_Txt);

    }//GEN-LAST:event_User_TxtKeyPressed

    private void Pass_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pass_TxtKeyPressed

        WinTool.WaitEnter(evt, Login_Btn);
    }//GEN-LAST:event_Pass_TxtKeyPressed

    private void MantenerS_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenerS_CBActionPerformed
        
        
       
    }//GEN-LAST:event_MantenerS_CBActionPerformed

    private void No_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_BtnActionPerformed
        
        FiTool.LimpiarFichero();
        jFrame1.setVisible(false);
        
    }//GEN-LAST:event_No_BtnActionPerformed

    private void Si_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Si_Btn1ActionPerformed
        
        jFrame1.setVisible(false);
        User_Txt.setText(FiTool.GetUserFichero());
        Pass_Txt.setText(FiTool.GetPassFichero());
        MantenerS_CB.setSelected(true);
        Login_Btn.doClick();
        
    }//GEN-LAST:event_Si_Btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo_Lbl;
    private javax.swing.JLabel Fondo_Lbl2;
    private javax.swing.JLabel ForgetPass_Lbl;
    private javax.swing.JButton Login_Btn;
    private javax.swing.JLabel Logo_Lbl;
    private javax.swing.JCheckBox MantenerS_CB;
    private javax.swing.JButton No_Btn;
    private javax.swing.JLabel Pass_Lbl;
    private javax.swing.JPasswordField Pass_Txt;
    private javax.swing.JButton Si_Btn1;
    private javax.swing.JLabel Titulo_Lbl;
    private javax.swing.JTextField User_Txt;
    private javax.swing.JLabel Username_Lbl;
    private javax.swing.JCheckBox VerPass_CB;
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables
}
