package ventanas;

import javax.swing.WindowConstants;
import javax.swing.JOptionPane;
import metodos.WindowTool;


public class Login_VerifyCode extends javax.swing.JFrame {

    WindowTool WinTool = new WindowTool();
    String RandomCode = Login_RecoverPass.RandomCode;
    int Cont = 2;
    
    public Login_VerifyCode() {
        
        initComponents();
        
        
        //Modelando ventana.
        this.setResizable(false);
        this.setTitle(" -  Código de verificación.");
        this.setSize(370, 250);
        this.setLocationRelativeTo(null);
        
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        
        //Setting fondo.
        Fondo_Lbl.setIcon(WinTool.SetFondo(Fondo_Lbl, "src/icons/Fondo2.jpg"));
        this.repaint();
        
        //Setting icon.
        this.setIconImage(WinTool.GetIconImage("icons/Logo.jpg"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Codigo_Txt = new javax.swing.JTextField();
        Verificar_Btn = new javax.swing.JButton();
        Fondo_Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("<html>Por favor, ingresa el código de verificación<p>que hemos enviado a tu correo electrónico.<html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 90));

        Codigo_Txt.setBackground(new java.awt.Color(51, 51, 51));
        Codigo_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Codigo_Txt.setForeground(new java.awt.Color(204, 204, 204));
        Codigo_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Codigo_TxtKeyPressed(evt);
            }
        });
        getContentPane().add(Codigo_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        Verificar_Btn.setBackground(new java.awt.Color(51, 51, 51));
        Verificar_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Verificar_Btn.setForeground(new java.awt.Color(204, 204, 204));
        Verificar_Btn.setText("Verificar");
        Verificar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verificar_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Verificar_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, -1));
        getContentPane().add(Fondo_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Codigo_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Codigo_TxtKeyPressed
        
        WinTool.WaitEnter(evt, Verificar_Btn);
        
    }//GEN-LAST:event_Codigo_TxtKeyPressed

    private void Verificar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verificar_BtnActionPerformed
        
        String InsertRandomCode;
        InsertRandomCode = Codigo_Txt.getText().trim();
        
        if(InsertRandomCode.equalsIgnoreCase(RandomCode)){
            
            this.dispose();
            new Login_ResetPass().setVisible(true);
            
            Login_RecoverPass.RandomCode = "";
            RandomCode = "";
            
        }else if(!InsertRandomCode.equalsIgnoreCase(RandomCode) && Cont > 0){
            
            JOptionPane.showMessageDialog(null, "Código incorrecto.\nIntentos restantes: "+ Cont,
                    " -  Mensaje de advertencia", 0, WinTool.GetIcon("src/JOIcons/Advertencia JO.png"));
            Cont--;
            
        }else if(!InsertRandomCode.equalsIgnoreCase(RandomCode) && Cont == 0){
            
            JOptionPane.showMessageDialog(null, "Número máximo de intentos.\nIntentos restantes: "+ Cont,
                    " -  Mensaje de error", 0, WinTool.GetIcon("src/JOIcons/Error JO.png"));
            this.dispose();
            
            Login_RecoverPass.RandomCode = "";
            RandomCode = "";
            
        }
        
        Codigo_Txt.setText("");
        Codigo_Txt.requestFocus();
        
    }//GEN-LAST:event_Verificar_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_VerifyCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_VerifyCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_VerifyCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_VerifyCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_VerifyCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo_Txt;
    private javax.swing.JLabel Fondo_Lbl;
    private javax.swing.JButton Verificar_Btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
